

vhdlan -xlrm "J:/GIT/FPGA_MODULATOR/Fir_test/ip/filter/firip_sim/dspba_library_package.vhd"                      
vhdlan -xlrm "J:/GIT/FPGA_MODULATOR/Fir_test/ip/filter/firip_sim/dspba_library.vhd"                              
vhdlan -xlrm "J:/GIT/FPGA_MODULATOR/Fir_test/ip/filter/firip_sim/auk_dspip_math_pkg_hpfir.vhd"                   
vhdlan -xlrm "J:/GIT/FPGA_MODULATOR/Fir_test/ip/filter/firip_sim/auk_dspip_lib_pkg_hpfir.vhd"                    
vhdlan -xlrm "J:/GIT/FPGA_MODULATOR/Fir_test/ip/filter/firip_sim/auk_dspip_avalon_streaming_controller_hpfir.vhd"
vhdlan -xlrm "J:/GIT/FPGA_MODULATOR/Fir_test/ip/filter/firip_sim/auk_dspip_avalon_streaming_sink_hpfir.vhd"      
vhdlan -xlrm "J:/GIT/FPGA_MODULATOR/Fir_test/ip/filter/firip_sim/auk_dspip_avalon_streaming_source_hpfir.vhd"    
vhdlan -xlrm "J:/GIT/FPGA_MODULATOR/Fir_test/ip/filter/firip_sim/auk_dspip_roundsat_hpfir.vhd"                   
vlogan +v2k  "J:/GIT/FPGA_MODULATOR/Fir_test/ip/filter/firip_sim/altera_avalon_sc_fifo.v"                        
vhdlan -xlrm "J:/GIT/FPGA_MODULATOR/Fir_test/ip/filter/firip_sim/firip_rtl_core.vhd"                             
vhdlan -xlrm "J:/GIT/FPGA_MODULATOR/Fir_test/ip/filter/firip_sim/firip_ast.vhd"                                  
vhdlan -xlrm "J:/GIT/FPGA_MODULATOR/Fir_test/ip/filter/firip_sim/firip.vhd"                                      
vhdlan -xlrm "J:/GIT/FPGA_MODULATOR/Fir_test/ip/filter/firip_sim/firip_tb.vhd"                                   
