// Generated by FIR Compiler
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
// ************************************************************
// Copyright (C) 1991-2004 Altera Corporation
// Any megafunction design, and related net list (encrypted or decrypted),
// support information, device programming or simulation file, and any other
// associated documentation or information provided by Altera or a partner
// under Altera's Megafunction Partnership Program may be used only to
// program PLD devices (but not masked PLD devices) from Altera.  Any other
// use of such megafunction design, net list, support information, device
// programming or simulation file, or any other related documentation or
// information is prohibited for any other purpose, including, but not
// limited to modification, reverse engineering, de-compiling, or use with
// any other silicon devices, unless such use is explicitly licensed under
// a separate agreement with Altera or a megafunction partner.  Title to
// the intellectual property, including patents, copyrights, trademarks,
// trade secrets, or maskworks, embodied in any such megafunction design,
// net list, support information, device programming or simulation file, or
// any other related documentation or information provided by Altera or a
// megafunction partner, remains with Altera, the megafunction partner, or
// their respective licensors.  No other licenses, including any licenses
// needed under any third party's intellectual property, are provided herein.
// 01
// altera message_off 10036
(* altera_attribute = "-name MESSAGE_DISABLE 15400; -name MESSAGE_DISABLE 14130; -name MESSAGE_DISABLE 10036; -name MESSAGE_DISABLE 12020; -name MESSAGE_DISABLE 12030; -name MESSAGE_DISABLE 12010; -name MESSAGE_DISABLE 12110; -name MESSAGE_DISABLE 14320; -name MESSAGE_DISABLE 13410" *)
module h_bpf_st (clk, 
              rst, 
              data_in, 
              clk_en, 
              done, 
              rdy_to_ld, 
              fir_result ); 

parameter DATA_WIDTH  = 8;
parameter COEF_WIDTH  = 9;
parameter COEF_WIDTH_IN  = 9;
parameter ACCUM_WIDTH = 18;

input clk, rst;
input [DATA_WIDTH -1 :0] data_in;
input clk_en;
output done;
wire done;
wire done_int;
wire data_ld;
output rdy_to_ld;
wire rdy_to_ld;
wire rdy_int;
output [ACCUM_WIDTH-1:0] fir_result;

wire acc_rst_out;
wire coef_in_clk;
assign coef_in_clk = clk;
wire [7:0] tdl_dat_0_n;
wire [7:0] tdl_dat_1_n;
wire [7:0] tdl_dat_2_n;
wire [7:0] tdl_dat_3_n;
wire [7:0] tdl_dat_4_n;
wire [7:0] tdl_dat_5_n;
wire [7:0] tdl_dat_6_n;
wire [7:0] tdl_dat_7_n;
wire [7:0] tdl_dat_8_n;
wire [7:0] tdl_dat_9_n;
wire [7:0] tdl_dat_10_n;
wire [7:0] tdl_dat_11_n;
wire [7:0] tdl_dat_12_n;
wire [7:0] tdl_dat_13_n;
wire [7:0] tdl_dat_14_n;
wire [7:0] tdl_dat_15_n;
wire [7:0] tdl_dat_16_n;
wire [7:0] tdl_dat_17_n;
wire [7:0] tdl_dat_18_n;
wire [7:0] tdl_dat_19_n;
wire [7:0] tdl_dat_20_n;
wire [7:0] tdl_dat_21_n;
wire [7:0] tdl_dat_22_n;
wire [7:0] tdl_dat_23_n;
wire [7:0] tdl_dat_24_n;
wire [7:0] tdl_dat_25_n;
wire [7:0] tdl_dat_26_n;
wire [7:0] tdl_dat_27_n;
wire [7:0] tdl_dat_28_n;
wire [7:0] tdl_dat_29_n;
wire [7:0] tdl_dat_30_n;
wire [7:0] tdl_dat_31_n;
wire [7:0] tdl_dat_31_n_pre;
wire [7:0] tdl_dat_16_n_ori;
wire [7:0] data_in_dd;
lc_store_cen Udin(.clk(clk), .rst(rst), .ce(rdy_int),.gclk_en(clk_en), .data_in(data_in),.q(data_in_dd) );
defparam Udin.WIDTH = 8;
tdl_da_lc tdl_ff_0_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(data_in_dd),.data_out(tdl_dat_0_n));
defparam tdl_ff_0_ch_0_n.WIDTH = 8;
tdl_da_lc tdl_ff_1_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_0_n),.data_out(tdl_dat_1_n));
defparam tdl_ff_1_ch_0_n.WIDTH = 8;
tdl_da_lc tdl_ff_2_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_1_n),.data_out(tdl_dat_2_n));
defparam tdl_ff_2_ch_0_n.WIDTH = 8;
tdl_da_lc tdl_ff_3_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_2_n),.data_out(tdl_dat_3_n));
defparam tdl_ff_3_ch_0_n.WIDTH = 8;
tdl_da_lc tdl_ff_4_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_3_n),.data_out(tdl_dat_4_n));
defparam tdl_ff_4_ch_0_n.WIDTH = 8;
tdl_da_lc tdl_ff_5_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_4_n),.data_out(tdl_dat_5_n));
defparam tdl_ff_5_ch_0_n.WIDTH = 8;
tdl_da_lc tdl_ff_6_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_5_n),.data_out(tdl_dat_6_n));
defparam tdl_ff_6_ch_0_n.WIDTH = 8;
tdl_da_lc tdl_ff_7_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_6_n),.data_out(tdl_dat_7_n));
defparam tdl_ff_7_ch_0_n.WIDTH = 8;
tdl_da_lc tdl_ff_8_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_7_n),.data_out(tdl_dat_8_n));
defparam tdl_ff_8_ch_0_n.WIDTH = 8;
tdl_da_lc tdl_ff_9_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_8_n),.data_out(tdl_dat_9_n));
defparam tdl_ff_9_ch_0_n.WIDTH = 8;
tdl_da_lc tdl_ff_10_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_9_n),.data_out(tdl_dat_10_n));
defparam tdl_ff_10_ch_0_n.WIDTH = 8;
tdl_da_lc tdl_ff_11_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_10_n),.data_out(tdl_dat_11_n));
defparam tdl_ff_11_ch_0_n.WIDTH = 8;
tdl_da_lc tdl_ff_12_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_11_n),.data_out(tdl_dat_12_n));
defparam tdl_ff_12_ch_0_n.WIDTH = 8;
tdl_da_lc tdl_ff_13_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_12_n),.data_out(tdl_dat_13_n));
defparam tdl_ff_13_ch_0_n.WIDTH = 8;
tdl_da_lc tdl_ff_14_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_13_n),.data_out(tdl_dat_14_n));
defparam tdl_ff_14_ch_0_n.WIDTH = 8;
tdl_da_lc tdl_ff_15_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_14_n),.data_out(tdl_dat_15_n));
defparam tdl_ff_15_ch_0_n.WIDTH = 8;
tdl_da_lc tdl_ff_16_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_15_n),.data_out(tdl_dat_16_n));
defparam tdl_ff_16_ch_0_n.WIDTH = 8;
tdl_da_lc tdl_ff_17_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_16_n),.data_out(tdl_dat_17_n));
defparam tdl_ff_17_ch_0_n.WIDTH = 8;
tdl_da_lc tdl_ff_18_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_17_n),.data_out(tdl_dat_18_n));
defparam tdl_ff_18_ch_0_n.WIDTH = 8;
tdl_da_lc tdl_ff_19_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_18_n),.data_out(tdl_dat_19_n));
defparam tdl_ff_19_ch_0_n.WIDTH = 8;
tdl_da_lc tdl_ff_20_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_19_n),.data_out(tdl_dat_20_n));
defparam tdl_ff_20_ch_0_n.WIDTH = 8;
tdl_da_lc tdl_ff_21_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_20_n),.data_out(tdl_dat_21_n));
defparam tdl_ff_21_ch_0_n.WIDTH = 8;
tdl_da_lc tdl_ff_22_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_21_n),.data_out(tdl_dat_22_n));
defparam tdl_ff_22_ch_0_n.WIDTH = 8;
tdl_da_lc tdl_ff_23_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_22_n),.data_out(tdl_dat_23_n));
defparam tdl_ff_23_ch_0_n.WIDTH = 8;
tdl_da_lc tdl_ff_24_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_23_n),.data_out(tdl_dat_24_n));
defparam tdl_ff_24_ch_0_n.WIDTH = 8;
tdl_da_lc tdl_ff_25_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_24_n),.data_out(tdl_dat_25_n));
defparam tdl_ff_25_ch_0_n.WIDTH = 8;
tdl_da_lc tdl_ff_26_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_25_n),.data_out(tdl_dat_26_n));
defparam tdl_ff_26_ch_0_n.WIDTH = 8;
tdl_da_lc tdl_ff_27_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_26_n),.data_out(tdl_dat_27_n));
defparam tdl_ff_27_ch_0_n.WIDTH = 8;
tdl_da_lc tdl_ff_28_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_27_n),.data_out(tdl_dat_28_n));
defparam tdl_ff_28_ch_0_n.WIDTH = 8;
tdl_da_lc tdl_ff_29_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_28_n),.data_out(tdl_dat_29_n));
defparam tdl_ff_29_ch_0_n.WIDTH = 8;
tdl_da_lc tdl_ff_30_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_29_n),.data_out(tdl_dat_30_n));
defparam tdl_ff_30_ch_0_n.WIDTH = 8;
tdl_da_lc tdl_ff_31_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_30_n),.data_out(tdl_dat_31_n));
defparam tdl_ff_31_ch_0_n.WIDTH = 8;

// symmetrical adders ...
wire [8:0] sym_res_0_n;
ssub_cen U_0_sym_add (.clk(clk), .gclk_en(clk_en), .ain(tdl_dat_0_n), .bin(tdl_dat_30_n), .res(sym_res_0_n) );
defparam U_0_sym_add.IN_WIDTH = 8;
defparam U_0_sym_add.PIPE_DEPTH = 1;
wire [8:0] sym_res_1_n;
ssub_cen U_1_sym_add (.clk(clk), .gclk_en(clk_en), .ain(tdl_dat_1_n), .bin(tdl_dat_29_n), .res(sym_res_1_n) );
defparam U_1_sym_add.IN_WIDTH = 8;
defparam U_1_sym_add.PIPE_DEPTH = 1;
wire [8:0] sym_res_2_n;
ssub_cen U_2_sym_add (.clk(clk), .gclk_en(clk_en), .ain(tdl_dat_2_n), .bin(tdl_dat_28_n), .res(sym_res_2_n) );
defparam U_2_sym_add.IN_WIDTH = 8;
defparam U_2_sym_add.PIPE_DEPTH = 1;
wire [8:0] sym_res_3_n;
ssub_cen U_3_sym_add (.clk(clk), .gclk_en(clk_en), .ain(tdl_dat_3_n), .bin(tdl_dat_27_n), .res(sym_res_3_n) );
defparam U_3_sym_add.IN_WIDTH = 8;
defparam U_3_sym_add.PIPE_DEPTH = 1;
wire [8:0] sym_res_4_n;
ssub_cen U_4_sym_add (.clk(clk), .gclk_en(clk_en), .ain(tdl_dat_4_n), .bin(tdl_dat_26_n), .res(sym_res_4_n) );
defparam U_4_sym_add.IN_WIDTH = 8;
defparam U_4_sym_add.PIPE_DEPTH = 1;
wire [8:0] sym_res_5_n;
ssub_cen U_5_sym_add (.clk(clk), .gclk_en(clk_en), .ain(tdl_dat_5_n), .bin(tdl_dat_25_n), .res(sym_res_5_n) );
defparam U_5_sym_add.IN_WIDTH = 8;
defparam U_5_sym_add.PIPE_DEPTH = 1;
wire [8:0] sym_res_6_n;
ssub_cen U_6_sym_add (.clk(clk), .gclk_en(clk_en), .ain(tdl_dat_6_n), .bin(tdl_dat_24_n), .res(sym_res_6_n) );
defparam U_6_sym_add.IN_WIDTH = 8;
defparam U_6_sym_add.PIPE_DEPTH = 1;
wire [8:0] sym_res_7_n;
ssub_cen U_7_sym_add (.clk(clk), .gclk_en(clk_en), .ain(tdl_dat_7_n), .bin(tdl_dat_23_n), .res(sym_res_7_n) );
defparam U_7_sym_add.IN_WIDTH = 8;
defparam U_7_sym_add.PIPE_DEPTH = 1;
wire [8:0] sym_res_8_n;
ssub_cen U_8_sym_add (.clk(clk), .gclk_en(clk_en), .ain(tdl_dat_8_n), .bin(tdl_dat_22_n), .res(sym_res_8_n) );
defparam U_8_sym_add.IN_WIDTH = 8;
defparam U_8_sym_add.PIPE_DEPTH = 1;
wire [8:0] sym_res_9_n;
ssub_cen U_9_sym_add (.clk(clk), .gclk_en(clk_en), .ain(tdl_dat_9_n), .bin(tdl_dat_21_n), .res(sym_res_9_n) );
defparam U_9_sym_add.IN_WIDTH = 8;
defparam U_9_sym_add.PIPE_DEPTH = 1;
wire [8:0] sym_res_10_n;
ssub_cen U_10_sym_add (.clk(clk), .gclk_en(clk_en), .ain(tdl_dat_10_n), .bin(tdl_dat_20_n), .res(sym_res_10_n) );
defparam U_10_sym_add.IN_WIDTH = 8;
defparam U_10_sym_add.PIPE_DEPTH = 1;
wire [8:0] sym_res_11_n;
ssub_cen U_11_sym_add (.clk(clk), .gclk_en(clk_en), .ain(tdl_dat_11_n), .bin(tdl_dat_19_n), .res(sym_res_11_n) );
defparam U_11_sym_add.IN_WIDTH = 8;
defparam U_11_sym_add.PIPE_DEPTH = 1;
wire [8:0] sym_res_12_n;
ssub_cen U_12_sym_add (.clk(clk), .gclk_en(clk_en), .ain(tdl_dat_12_n), .bin(tdl_dat_18_n), .res(sym_res_12_n) );
defparam U_12_sym_add.IN_WIDTH = 8;
defparam U_12_sym_add.PIPE_DEPTH = 1;
wire [8:0] sym_res_13_n;
ssub_cen U_13_sym_add (.clk(clk), .gclk_en(clk_en), .ain(tdl_dat_13_n), .bin(tdl_dat_17_n), .res(sym_res_13_n) );
defparam U_13_sym_add.IN_WIDTH = 8;
defparam U_13_sym_add.PIPE_DEPTH = 1;
wire [8:0] sym_res_14_n;
ssub_cen U_14_sym_add (.clk(clk), .gclk_en(clk_en), .ain(tdl_dat_14_n), .bin(tdl_dat_16_n), .res(sym_res_14_n) );
defparam U_14_sym_add.IN_WIDTH = 8;
defparam U_14_sym_add.PIPE_DEPTH = 1;
wire [8:0] sym_res_15_n;
ssub_cen U_15_sym_add (.clk(clk), .gclk_en(clk_en), .ain(tdl_dat_15_n), .bin(8'd0), .res(sym_res_15_n) );
defparam U_15_sym_add.IN_WIDTH = 8;
defparam U_15_sym_add.PIPE_DEPTH = 1;


wire coef_en ;
assign coef_en = clk_en;
wire [8:0] coef_st_comb_0_n;
wire [COEF_WIDTH-1:0]coef_st_0_n;
assign coef_st_0_n = coef_st_comb_0_n[8:0];
msft_lt_32 Ucoef_0_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(9'b0), .data_out(coef_st_comb_0_n));
defparam Ucoef_0_n.WIDTH = COEF_WIDTH;
defparam Ucoef_0_n.LENGTH = 1;
defparam Ucoef_0_n.DELAY = 0;
defparam Ucoef_0_n.C0 = 511;
wire [8:0] coef_st_comb_1_n;
wire [COEF_WIDTH-1:0]coef_st_1_n;
assign coef_st_1_n = coef_st_comb_1_n[8:0];
msft_lt_32 Ucoef_1_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(9'b0), .data_out(coef_st_comb_1_n));
defparam Ucoef_1_n.WIDTH = COEF_WIDTH;
defparam Ucoef_1_n.LENGTH = 1;
defparam Ucoef_1_n.DELAY = 0;
defparam Ucoef_1_n.C0 = 0;
wire [8:0] coef_st_comb_2_n;
wire [COEF_WIDTH-1:0]coef_st_2_n;
assign coef_st_2_n = coef_st_comb_2_n[8:0];
msft_lt_32 Ucoef_2_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(9'b0), .data_out(coef_st_comb_2_n));
defparam Ucoef_2_n.WIDTH = COEF_WIDTH;
defparam Ucoef_2_n.LENGTH = 1;
defparam Ucoef_2_n.DELAY = 0;
defparam Ucoef_2_n.C0 = 507;
wire [8:0] coef_st_comb_3_n;
wire [COEF_WIDTH-1:0]coef_st_3_n;
assign coef_st_3_n = coef_st_comb_3_n[8:0];
msft_lt_32 Ucoef_3_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(9'b0), .data_out(coef_st_comb_3_n));
defparam Ucoef_3_n.WIDTH = COEF_WIDTH;
defparam Ucoef_3_n.LENGTH = 1;
defparam Ucoef_3_n.DELAY = 0;
defparam Ucoef_3_n.C0 = 0;
wire [8:0] coef_st_comb_4_n;
wire [COEF_WIDTH-1:0]coef_st_4_n;
assign coef_st_4_n = coef_st_comb_4_n[8:0];
msft_lt_32 Ucoef_4_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(9'b0), .data_out(coef_st_comb_4_n));
defparam Ucoef_4_n.WIDTH = COEF_WIDTH;
defparam Ucoef_4_n.LENGTH = 1;
defparam Ucoef_4_n.DELAY = 0;
defparam Ucoef_4_n.C0 = 507;
wire [8:0] coef_st_comb_5_n;
wire [COEF_WIDTH-1:0]coef_st_5_n;
assign coef_st_5_n = coef_st_comb_5_n[8:0];
msft_lt_32 Ucoef_5_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(9'b0), .data_out(coef_st_comb_5_n));
defparam Ucoef_5_n.WIDTH = COEF_WIDTH;
defparam Ucoef_5_n.LENGTH = 1;
defparam Ucoef_5_n.DELAY = 0;
defparam Ucoef_5_n.C0 = 0;
wire [8:0] coef_st_comb_6_n;
wire [COEF_WIDTH-1:0]coef_st_6_n;
assign coef_st_6_n = coef_st_comb_6_n[8:0];
msft_lt_32 Ucoef_6_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(9'b0), .data_out(coef_st_comb_6_n));
defparam Ucoef_6_n.WIDTH = COEF_WIDTH;
defparam Ucoef_6_n.LENGTH = 1;
defparam Ucoef_6_n.DELAY = 0;
defparam Ucoef_6_n.C0 = 6;
wire [8:0] coef_st_comb_7_n;
wire [COEF_WIDTH-1:0]coef_st_7_n;
assign coef_st_7_n = coef_st_comb_7_n[8:0];
msft_lt_32 Ucoef_7_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(9'b0), .data_out(coef_st_comb_7_n));
defparam Ucoef_7_n.WIDTH = COEF_WIDTH;
defparam Ucoef_7_n.LENGTH = 1;
defparam Ucoef_7_n.DELAY = 0;
defparam Ucoef_7_n.C0 = 0;
wire [8:0] coef_st_comb_8_n;
wire [COEF_WIDTH-1:0]coef_st_8_n;
assign coef_st_8_n = coef_st_comb_8_n[8:0];
msft_lt_32 Ucoef_8_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(9'b0), .data_out(coef_st_comb_8_n));
defparam Ucoef_8_n.WIDTH = COEF_WIDTH;
defparam Ucoef_8_n.LENGTH = 1;
defparam Ucoef_8_n.DELAY = 0;
defparam Ucoef_8_n.C0 = 27;
wire [8:0] coef_st_comb_9_n;
wire [COEF_WIDTH-1:0]coef_st_9_n;
assign coef_st_9_n = coef_st_comb_9_n[8:0];
msft_lt_32 Ucoef_9_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(9'b0), .data_out(coef_st_comb_9_n));
defparam Ucoef_9_n.WIDTH = COEF_WIDTH;
defparam Ucoef_9_n.LENGTH = 1;
defparam Ucoef_9_n.DELAY = 0;
defparam Ucoef_9_n.C0 = 0;
wire [8:0] coef_st_comb_10_n;
wire [COEF_WIDTH-1:0]coef_st_10_n;
assign coef_st_10_n = coef_st_comb_10_n[8:0];
msft_lt_32 Ucoef_10_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(9'b0), .data_out(coef_st_comb_10_n));
defparam Ucoef_10_n.WIDTH = COEF_WIDTH;
defparam Ucoef_10_n.LENGTH = 1;
defparam Ucoef_10_n.DELAY = 0;
defparam Ucoef_10_n.C0 = 36;
wire [8:0] coef_st_comb_11_n;
wire [COEF_WIDTH-1:0]coef_st_11_n;
assign coef_st_11_n = coef_st_comb_11_n[8:0];
msft_lt_32 Ucoef_11_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(9'b0), .data_out(coef_st_comb_11_n));
defparam Ucoef_11_n.WIDTH = COEF_WIDTH;
defparam Ucoef_11_n.LENGTH = 1;
defparam Ucoef_11_n.DELAY = 0;
defparam Ucoef_11_n.C0 = 0;
wire [8:0] coef_st_comb_12_n;
wire [COEF_WIDTH-1:0]coef_st_12_n;
assign coef_st_12_n = coef_st_comb_12_n[8:0];
msft_lt_32 Ucoef_12_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(9'b0), .data_out(coef_st_comb_12_n));
defparam Ucoef_12_n.WIDTH = COEF_WIDTH;
defparam Ucoef_12_n.LENGTH = 1;
defparam Ucoef_12_n.DELAY = 0;
defparam Ucoef_12_n.C0 = 502;
wire [8:0] coef_st_comb_13_n;
wire [COEF_WIDTH-1:0]coef_st_13_n;
assign coef_st_13_n = coef_st_comb_13_n[8:0];
msft_lt_32 Ucoef_13_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(9'b0), .data_out(coef_st_comb_13_n));
defparam Ucoef_13_n.WIDTH = COEF_WIDTH;
defparam Ucoef_13_n.LENGTH = 1;
defparam Ucoef_13_n.DELAY = 0;
defparam Ucoef_13_n.C0 = 0;
wire [8:0] coef_st_comb_14_n;
wire [COEF_WIDTH-1:0]coef_st_14_n;
assign coef_st_14_n = coef_st_comb_14_n[8:0];
msft_lt_32 Ucoef_14_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(9'b0), .data_out(coef_st_comb_14_n));
defparam Ucoef_14_n.WIDTH = COEF_WIDTH;
defparam Ucoef_14_n.LENGTH = 1;
defparam Ucoef_14_n.DELAY = 0;
defparam Ucoef_14_n.C0 = 257;
wire [8:0] coef_st_comb_15_n;
wire [COEF_WIDTH-1:0]coef_st_15_n;
assign coef_st_15_n = coef_st_comb_15_n[8:0];
msft_lt_32 Ucoef_15_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(9'b0), .data_out(coef_st_comb_15_n));
defparam Ucoef_15_n.WIDTH = COEF_WIDTH;
defparam Ucoef_15_n.LENGTH = 1;
defparam Ucoef_15_n.DELAY = 0;
defparam Ucoef_15_n.C0 = 0;


wire [17:0] mlu_resx_0_n;
mlu_inf_2reg Umlu_0_n (.clk(clk), .data_in(sym_res_0_n), .coef_in(coef_st_0_n), .clk_en(clk_en), .mlu_out(mlu_resx_0_n) );
defparam Umlu_0_n.DATA_WIDTH = 9;
defparam Umlu_0_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_0_n.PIPE = 2;
defparam Umlu_0_n.DSP_USE = "YES";
wire [17:0] mlu_res_0_n;
mac_tl Umtl_0_n             (.clk(clk), 
             .data_in(mlu_resx_0_n),
             .data_out(mlu_res_0_n));
defparam Umtl_0_n.DATA_WIDTH = 18;

wire [17:0] mlu_resx_1_n;
mlu_inf_2reg Umlu_1_n (.clk(clk), .data_in(sym_res_1_n), .coef_in(coef_st_1_n), .clk_en(clk_en), .mlu_out(mlu_resx_1_n) );
defparam Umlu_1_n.DATA_WIDTH = 9;
defparam Umlu_1_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_1_n.PIPE = 2;
defparam Umlu_1_n.DSP_USE = "YES";
wire [17:0] mlu_res_1_n;
mac_tl Umtl_1_n             (.clk(clk), 
             .data_in(mlu_resx_1_n),
             .data_out(mlu_res_1_n));
defparam Umtl_1_n.DATA_WIDTH = 18;

wire [17:0] mlu_resx_2_n;
mlu_inf_2reg Umlu_2_n (.clk(clk), .data_in(sym_res_2_n), .coef_in(coef_st_2_n), .clk_en(clk_en), .mlu_out(mlu_resx_2_n) );
defparam Umlu_2_n.DATA_WIDTH = 9;
defparam Umlu_2_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_2_n.PIPE = 2;
defparam Umlu_2_n.DSP_USE = "YES";
wire [17:0] mlu_res_2_n;
mac_tl Umtl_2_n             (.clk(clk), 
             .data_in(mlu_resx_2_n),
             .data_out(mlu_res_2_n));
defparam Umtl_2_n.DATA_WIDTH = 18;

wire [17:0] mlu_resx_3_n;
mlu_inf_2reg Umlu_3_n (.clk(clk), .data_in(sym_res_3_n), .coef_in(coef_st_3_n), .clk_en(clk_en), .mlu_out(mlu_resx_3_n) );
defparam Umlu_3_n.DATA_WIDTH = 9;
defparam Umlu_3_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_3_n.PIPE = 2;
defparam Umlu_3_n.DSP_USE = "YES";
wire [17:0] mlu_res_3_n;
mac_tl Umtl_3_n             (.clk(clk), 
             .data_in(mlu_resx_3_n),
             .data_out(mlu_res_3_n));
defparam Umtl_3_n.DATA_WIDTH = 18;

wire [17:0] mlu_resx_4_n;
mlu_inf_2reg Umlu_4_n (.clk(clk), .data_in(sym_res_4_n), .coef_in(coef_st_4_n), .clk_en(clk_en), .mlu_out(mlu_resx_4_n) );
defparam Umlu_4_n.DATA_WIDTH = 9;
defparam Umlu_4_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_4_n.PIPE = 2;
defparam Umlu_4_n.DSP_USE = "YES";
wire [17:0] mlu_res_4_n;
mac_tl Umtl_4_n             (.clk(clk), 
             .data_in(mlu_resx_4_n),
             .data_out(mlu_res_4_n));
defparam Umtl_4_n.DATA_WIDTH = 18;

wire [17:0] mlu_resx_5_n;
mlu_inf_2reg Umlu_5_n (.clk(clk), .data_in(sym_res_5_n), .coef_in(coef_st_5_n), .clk_en(clk_en), .mlu_out(mlu_resx_5_n) );
defparam Umlu_5_n.DATA_WIDTH = 9;
defparam Umlu_5_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_5_n.PIPE = 2;
defparam Umlu_5_n.DSP_USE = "YES";
wire [17:0] mlu_res_5_n;
mac_tl Umtl_5_n             (.clk(clk), 
             .data_in(mlu_resx_5_n),
             .data_out(mlu_res_5_n));
defparam Umtl_5_n.DATA_WIDTH = 18;

wire [17:0] mlu_resx_6_n;
mlu_inf_2reg Umlu_6_n (.clk(clk), .data_in(sym_res_6_n), .coef_in(coef_st_6_n), .clk_en(clk_en), .mlu_out(mlu_resx_6_n) );
defparam Umlu_6_n.DATA_WIDTH = 9;
defparam Umlu_6_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_6_n.PIPE = 2;
defparam Umlu_6_n.DSP_USE = "YES";
wire [17:0] mlu_res_6_n;
mac_tl Umtl_6_n             (.clk(clk), 
             .data_in(mlu_resx_6_n),
             .data_out(mlu_res_6_n));
defparam Umtl_6_n.DATA_WIDTH = 18;

wire [17:0] mlu_resx_7_n;
mlu_inf_2reg Umlu_7_n (.clk(clk), .data_in(sym_res_7_n), .coef_in(coef_st_7_n), .clk_en(clk_en), .mlu_out(mlu_resx_7_n) );
defparam Umlu_7_n.DATA_WIDTH = 9;
defparam Umlu_7_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_7_n.PIPE = 2;
defparam Umlu_7_n.DSP_USE = "YES";
wire [17:0] mlu_res_7_n;
mac_tl Umtl_7_n             (.clk(clk), 
             .data_in(mlu_resx_7_n),
             .data_out(mlu_res_7_n));
defparam Umtl_7_n.DATA_WIDTH = 18;

wire [17:0] mlu_resx_8_n;
mlu_inf_2reg Umlu_8_n (.clk(clk), .data_in(sym_res_8_n), .coef_in(coef_st_8_n), .clk_en(clk_en), .mlu_out(mlu_resx_8_n) );
defparam Umlu_8_n.DATA_WIDTH = 9;
defparam Umlu_8_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_8_n.PIPE = 2;
defparam Umlu_8_n.DSP_USE = "YES";
wire [17:0] mlu_res_8_n;
mac_tl Umtl_8_n             (.clk(clk), 
             .data_in(mlu_resx_8_n),
             .data_out(mlu_res_8_n));
defparam Umtl_8_n.DATA_WIDTH = 18;

wire [17:0] mlu_resx_9_n;
mlu_inf_2reg Umlu_9_n (.clk(clk), .data_in(sym_res_9_n), .coef_in(coef_st_9_n), .clk_en(clk_en), .mlu_out(mlu_resx_9_n) );
defparam Umlu_9_n.DATA_WIDTH = 9;
defparam Umlu_9_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_9_n.PIPE = 2;
defparam Umlu_9_n.DSP_USE = "YES";
wire [17:0] mlu_res_9_n;
mac_tl Umtl_9_n             (.clk(clk), 
             .data_in(mlu_resx_9_n),
             .data_out(mlu_res_9_n));
defparam Umtl_9_n.DATA_WIDTH = 18;

wire [17:0] mlu_resx_10_n;
mlu_inf_2reg Umlu_10_n (.clk(clk), .data_in(sym_res_10_n), .coef_in(coef_st_10_n), .clk_en(clk_en), .mlu_out(mlu_resx_10_n) );
defparam Umlu_10_n.DATA_WIDTH = 9;
defparam Umlu_10_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_10_n.PIPE = 2;
defparam Umlu_10_n.DSP_USE = "YES";
wire [17:0] mlu_res_10_n;
mac_tl Umtl_10_n             (.clk(clk), 
             .data_in(mlu_resx_10_n),
             .data_out(mlu_res_10_n));
defparam Umtl_10_n.DATA_WIDTH = 18;

wire [17:0] mlu_resx_11_n;
mlu_inf_2reg Umlu_11_n (.clk(clk), .data_in(sym_res_11_n), .coef_in(coef_st_11_n), .clk_en(clk_en), .mlu_out(mlu_resx_11_n) );
defparam Umlu_11_n.DATA_WIDTH = 9;
defparam Umlu_11_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_11_n.PIPE = 2;
defparam Umlu_11_n.DSP_USE = "YES";
wire [17:0] mlu_res_11_n;
mac_tl Umtl_11_n             (.clk(clk), 
             .data_in(mlu_resx_11_n),
             .data_out(mlu_res_11_n));
defparam Umtl_11_n.DATA_WIDTH = 18;

wire [17:0] mlu_resx_12_n;
mlu_inf_2reg Umlu_12_n (.clk(clk), .data_in(sym_res_12_n), .coef_in(coef_st_12_n), .clk_en(clk_en), .mlu_out(mlu_resx_12_n) );
defparam Umlu_12_n.DATA_WIDTH = 9;
defparam Umlu_12_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_12_n.PIPE = 2;
defparam Umlu_12_n.DSP_USE = "YES";
wire [17:0] mlu_res_12_n;
mac_tl Umtl_12_n             (.clk(clk), 
             .data_in(mlu_resx_12_n),
             .data_out(mlu_res_12_n));
defparam Umtl_12_n.DATA_WIDTH = 18;

wire [17:0] mlu_resx_13_n;
mlu_inf_2reg Umlu_13_n (.clk(clk), .data_in(sym_res_13_n), .coef_in(coef_st_13_n), .clk_en(clk_en), .mlu_out(mlu_resx_13_n) );
defparam Umlu_13_n.DATA_WIDTH = 9;
defparam Umlu_13_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_13_n.PIPE = 2;
defparam Umlu_13_n.DSP_USE = "YES";
wire [17:0] mlu_res_13_n;
mac_tl Umtl_13_n             (.clk(clk), 
             .data_in(mlu_resx_13_n),
             .data_out(mlu_res_13_n));
defparam Umtl_13_n.DATA_WIDTH = 18;

wire [17:0] mlu_resx_14_n;
mlu_inf_2reg Umlu_14_n (.clk(clk), .data_in(sym_res_14_n), .coef_in(coef_st_14_n), .clk_en(clk_en), .mlu_out(mlu_resx_14_n) );
defparam Umlu_14_n.DATA_WIDTH = 9;
defparam Umlu_14_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_14_n.PIPE = 2;
defparam Umlu_14_n.DSP_USE = "YES";
wire [17:0] mlu_res_14_n;
mac_tl Umtl_14_n             (.clk(clk), 
             .data_in(mlu_resx_14_n),
             .data_out(mlu_res_14_n));
defparam Umtl_14_n.DATA_WIDTH = 18;

wire [17:0] mlu_resx_15_n;
mlu_inf_2reg Umlu_15_n (.clk(clk), .data_in(sym_res_15_n), .coef_in(coef_st_15_n), .clk_en(clk_en), .mlu_out(mlu_resx_15_n) );
defparam Umlu_15_n.DATA_WIDTH = 9;
defparam Umlu_15_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_15_n.PIPE = 2;
defparam Umlu_15_n.DSP_USE = "YES";
wire [17:0] mlu_res_15_n;
mac_tl Umtl_15_n             (.clk(clk), 
             .data_in(mlu_resx_15_n),
             .data_out(mlu_res_15_n));
defparam Umtl_15_n.DATA_WIDTH = 18;

wire [18:0] tree_l_0_n_0_n;
sadd_c_cen Uaddl_0_n_0_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_0_n), .bin(mlu_res_1_n), .res(tree_l_0_n_0_n) );
defparam Uaddl_0_n_0_n.IN_WIDTH = 18;
defparam Uaddl_0_n_0_n.PIPE_DEPTH = 1;
wire [18:0] tree_l_0_n_1_n;
sadd_c_cen Uaddl_0_n_1_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_2_n), .bin(mlu_res_3_n), .res(tree_l_0_n_1_n) );
defparam Uaddl_0_n_1_n.IN_WIDTH = 18;
defparam Uaddl_0_n_1_n.PIPE_DEPTH = 1;
wire [18:0] tree_l_0_n_2_n;
sadd_c_cen Uaddl_0_n_2_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_4_n), .bin(mlu_res_5_n), .res(tree_l_0_n_2_n) );
defparam Uaddl_0_n_2_n.IN_WIDTH = 18;
defparam Uaddl_0_n_2_n.PIPE_DEPTH = 1;
wire [18:0] tree_l_0_n_3_n;
sadd_c_cen Uaddl_0_n_3_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_6_n), .bin(mlu_res_7_n), .res(tree_l_0_n_3_n) );
defparam Uaddl_0_n_3_n.IN_WIDTH = 18;
defparam Uaddl_0_n_3_n.PIPE_DEPTH = 1;
wire [18:0] tree_l_0_n_4_n;
sadd_c_cen Uaddl_0_n_4_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_8_n), .bin(mlu_res_9_n), .res(tree_l_0_n_4_n) );
defparam Uaddl_0_n_4_n.IN_WIDTH = 18;
defparam Uaddl_0_n_4_n.PIPE_DEPTH = 1;
wire [18:0] tree_l_0_n_5_n;
sadd_c_cen Uaddl_0_n_5_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_10_n), .bin(mlu_res_11_n), .res(tree_l_0_n_5_n) );
defparam Uaddl_0_n_5_n.IN_WIDTH = 18;
defparam Uaddl_0_n_5_n.PIPE_DEPTH = 1;
wire [18:0] tree_l_0_n_6_n;
sadd_c_cen Uaddl_0_n_6_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_12_n), .bin(mlu_res_13_n), .res(tree_l_0_n_6_n) );
defparam Uaddl_0_n_6_n.IN_WIDTH = 18;
defparam Uaddl_0_n_6_n.PIPE_DEPTH = 1;
wire [18:0] tree_l_0_n_7_n;
sadd_c_cen Uaddl_0_n_7_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_14_n), .bin(mlu_res_15_n), .res(tree_l_0_n_7_n) );
defparam Uaddl_0_n_7_n.IN_WIDTH = 18;
defparam Uaddl_0_n_7_n.PIPE_DEPTH = 1;

wire [19:0] tree_l_1_n_0_n;
sadd_cen Uaddl_1_n_0_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_0_n_0_n), .bin(tree_l_0_n_1_n), .res(tree_l_1_n_0_n) );
defparam Uaddl_1_n_0_n.IN_WIDTH = 19;
defparam Uaddl_1_n_0_n.PIPE_DEPTH = 1;
wire [19:0] tree_l_1_n_1_n;
sadd_cen Uaddl_1_n_1_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_0_n_2_n), .bin(tree_l_0_n_3_n), .res(tree_l_1_n_1_n) );
defparam Uaddl_1_n_1_n.IN_WIDTH = 19;
defparam Uaddl_1_n_1_n.PIPE_DEPTH = 1;
wire [19:0] tree_l_1_n_2_n;
sadd_cen Uaddl_1_n_2_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_0_n_4_n), .bin(tree_l_0_n_5_n), .res(tree_l_1_n_2_n) );
defparam Uaddl_1_n_2_n.IN_WIDTH = 19;
defparam Uaddl_1_n_2_n.PIPE_DEPTH = 1;
wire [19:0] tree_l_1_n_3_n;
sadd_cen Uaddl_1_n_3_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_0_n_6_n), .bin(tree_l_0_n_7_n), .res(tree_l_1_n_3_n) );
defparam Uaddl_1_n_3_n.IN_WIDTH = 19;
defparam Uaddl_1_n_3_n.PIPE_DEPTH = 1;

wire [20:0] tree_l_2_n_0_n;
sadd_reg_top_cen Uaddl_2_n_0_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_1_n_0_n), .bin(tree_l_1_n_1_n), .res(tree_l_2_n_0_n) );
defparam Uaddl_2_n_0_n.IN_WIDTH = 20;
defparam Uaddl_2_n_0_n.PIPE_DEPTH = 1;
wire [20:0] tree_l_2_n_1_n;
sadd_reg_top_cen Uaddl_2_n_1_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_1_n_2_n), .bin(tree_l_1_n_3_n), .res(tree_l_2_n_1_n) );
defparam Uaddl_2_n_1_n.IN_WIDTH = 20;
defparam Uaddl_2_n_1_n.PIPE_DEPTH = 1;

wire [21:0] tree_l_3_n_0_n;
sadd_reg_top_cen Uaddl_3_n_0_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_2_n_0_n), .bin(tree_l_2_n_1_n), .res(tree_l_3_n_0_n) );
defparam Uaddl_3_n_0_n.IN_WIDTH = 21;
defparam Uaddl_3_n_0_n.PIPE_DEPTH = 1;

wire [21:0] fir_mc_res;
assign fir_mc_res=tree_l_3_n_0_n;
wire [17:0] fir_temp_res;
assign fir_temp_res = fir_mc_res[ACCUM_WIDTH-1:0];
wire [17:0] fir_int_res;
lc_store_cen Ures_reg (.clk(clk), .ce(done_int), .rst(rst), .gclk_en(clk_en),.data_in(fir_temp_res[ACCUM_WIDTH-1:0]), .q(fir_int_res) );
defparam Ures_reg.WIDTH = ACCUM_WIDTH;
assign fir_result = fir_int_res;
scv_ctrl ctrl(.rst(rst), .clk(clk), .clk_en(clk_en), .done_int(done_int), .rdy_int(rdy_int), .coef_ld(coef_ld), 
.done(done), .data_ld(data_ld), .rdy_to_ld(rdy_to_ld));
defparam ctrl.REG_LEN   = 1;
defparam ctrl.PIPE_DLY  = 9;
defparam ctrl.NO_SYM   = 0; 

endmodule
