

ncvhdl -v93 "J:/GIT/FPGA_MODULATOR/Fir_test/ip/filter/firip_sim/dspba_library_package.vhd"                      
ncvhdl -v93 "J:/GIT/FPGA_MODULATOR/Fir_test/ip/filter/firip_sim/dspba_library.vhd"                              
ncvhdl -v93 "J:/GIT/FPGA_MODULATOR/Fir_test/ip/filter/firip_sim/auk_dspip_math_pkg_hpfir.vhd"                   
ncvhdl -v93 "J:/GIT/FPGA_MODULATOR/Fir_test/ip/filter/firip_sim/auk_dspip_lib_pkg_hpfir.vhd"                    
ncvhdl -v93 "J:/GIT/FPGA_MODULATOR/Fir_test/ip/filter/firip_sim/auk_dspip_avalon_streaming_controller_hpfir.vhd"
ncvhdl -v93 "J:/GIT/FPGA_MODULATOR/Fir_test/ip/filter/firip_sim/auk_dspip_avalon_streaming_sink_hpfir.vhd"      
ncvhdl -v93 "J:/GIT/FPGA_MODULATOR/Fir_test/ip/filter/firip_sim/auk_dspip_avalon_streaming_source_hpfir.vhd"    
ncvhdl -v93 "J:/GIT/FPGA_MODULATOR/Fir_test/ip/filter/firip_sim/auk_dspip_roundsat_hpfir.vhd"                   
ncvlog      "J:/GIT/FPGA_MODULATOR/Fir_test/ip/filter/firip_sim/altera_avalon_sc_fifo.v"                        
ncvhdl -v93 "J:/GIT/FPGA_MODULATOR/Fir_test/ip/filter/firip_sim/firip_rtl_core.vhd"                             
ncvhdl -v93 "J:/GIT/FPGA_MODULATOR/Fir_test/ip/filter/firip_sim/firip_ast.vhd"                                  
ncvhdl -v93 "J:/GIT/FPGA_MODULATOR/Fir_test/ip/filter/firip_sim/firip.vhd"                                      
ncvhdl -v93 "J:/GIT/FPGA_MODULATOR/Fir_test/ip/filter/firip_sim/firip_tb.vhd"                                   
