

vcom "J:/GIT/FPGA_MODULATOR/Fir_test/ip/filter/firip_sim/dspba_library_package.vhd"                      
vcom "J:/GIT/FPGA_MODULATOR/Fir_test/ip/filter/firip_sim/dspba_library.vhd"                              
vcom "J:/GIT/FPGA_MODULATOR/Fir_test/ip/filter/firip_sim/auk_dspip_math_pkg_hpfir.vhd"                   
vcom "J:/GIT/FPGA_MODULATOR/Fir_test/ip/filter/firip_sim/auk_dspip_lib_pkg_hpfir.vhd"                    
vcom "J:/GIT/FPGA_MODULATOR/Fir_test/ip/filter/firip_sim/auk_dspip_avalon_streaming_controller_hpfir.vhd"
vcom "J:/GIT/FPGA_MODULATOR/Fir_test/ip/filter/firip_sim/auk_dspip_avalon_streaming_sink_hpfir.vhd"      
vcom "J:/GIT/FPGA_MODULATOR/Fir_test/ip/filter/firip_sim/auk_dspip_avalon_streaming_source_hpfir.vhd"    
vcom "J:/GIT/FPGA_MODULATOR/Fir_test/ip/filter/firip_sim/auk_dspip_roundsat_hpfir.vhd"                   
vlog "J:/GIT/FPGA_MODULATOR/Fir_test/ip/filter/firip_sim/altera_avalon_sc_fifo.v"                        
vcom "J:/GIT/FPGA_MODULATOR/Fir_test/ip/filter/firip_sim/firip_rtl_core.vhd"                             
vcom "J:/GIT/FPGA_MODULATOR/Fir_test/ip/filter/firip_sim/firip_ast.vhd"                                  
vcom "J:/GIT/FPGA_MODULATOR/Fir_test/ip/filter/firip_sim/firip.vhd"                                      
vcom "J:/GIT/FPGA_MODULATOR/Fir_test/ip/filter/firip_sim/firip_tb.vhd"                                   
