// Generated by FIR Compiler
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
// ************************************************************
// Copyright (C) 1991-2004 Altera Corporation
// Any megafunction design, and related net list (encrypted or decrypted),
// support information, device programming or simulation file, and any other
// associated documentation or information provided by Altera or a partner
// under Altera's Megafunction Partnership Program may be used only to
// program PLD devices (but not masked PLD devices) from Altera.  Any other
// use of such megafunction design, net list, support information, device
// programming or simulation file, or any other related documentation or
// information is prohibited for any other purpose, including, but not
// limited to modification, reverse engineering, de-compiling, or use with
// any other silicon devices, unless such use is explicitly licensed under
// a separate agreement with Altera or a megafunction partner.  Title to
// the intellectual property, including patents, copyrights, trademarks,
// trade secrets, or maskworks, embodied in any such megafunction design,
// net list, support information, device programming or simulation file, or
// any other related documentation or information provided by Altera or a
// megafunction partner, remains with Altera, the megafunction partner, or
// their respective licensors.  No other licenses, including any licenses
// needed under any third party's intellectual property, are provided herein.
// 01
// altera message_off 10036
(* altera_attribute = "-name MESSAGE_DISABLE 15400; -name MESSAGE_DISABLE 14130; -name MESSAGE_DISABLE 10036; -name MESSAGE_DISABLE 12020; -name MESSAGE_DISABLE 12030; -name MESSAGE_DISABLE 12010; -name MESSAGE_DISABLE 12110; -name MESSAGE_DISABLE 14320; -name MESSAGE_DISABLE 13410" *)
module fir_st (clk, 
              rst, 
              data_in, 
              clk_en, 
              done, 
              rdy_to_ld, 
              fir_result ); 

parameter DATA_WIDTH  = 12;
parameter COEF_WIDTH  = 12;
parameter COEF_WIDTH_IN  = 12;
parameter ACCUM_WIDTH = 25;

input clk, rst;
input [DATA_WIDTH -1 :0] data_in;
input clk_en;
output done;
wire done;
wire done_int;
wire data_ld;
output rdy_to_ld;
wire rdy_to_ld;
wire rdy_int;
output [ACCUM_WIDTH-1:0] fir_result;

wire acc_rst_out;
wire coef_in_clk;
assign coef_in_clk = clk;
wire [11:0] tdl_dat_0_n;
wire [11:0] tdl_dat_1_n;
wire [11:0] tdl_dat_2_n;
wire [11:0] tdl_dat_3_n;
wire [11:0] tdl_dat_4_n;
wire [11:0] tdl_dat_5_n;
wire [11:0] tdl_dat_5_n_pre;
wire [11:0] tdl_dat_3_n_ori;
wire [11:0] data_in_mux;
mux_2to1_cen tdl_mux(.clk(clk), .rst(rst), .gclk_en(clk_en), .bin(tdl_dat_2_n), .ain(data_in),
 .data_out(data_in_mux), .sel(rdy_int));
defparam tdl_mux.IN_WIDTH = 12;
wire [11:0] data_in_mux2;
mux_2to1_comb tdl_mux2(.rst(rst), .bin(tdl_dat_5_n_pre), .ain(tdl_dat_1_n),
 .data_out(data_in_mux2),.sel(rdy_int));
defparam tdl_mux2.IN_WIDTH = 12;
msft_data tdl_ff_0_ch_0_n(.rst(rst), .clk(clk), .clk_en(clk_en), .we(data_ld), .data_in(data_in_mux),.data_out(tdl_dat_0_n));
defparam tdl_ff_0_ch_0_n.WIDTH = 12;
defparam tdl_ff_0_ch_0_n.LENGTH = 4;
defparam tdl_ff_0_ch_0_n.DELAY = 0;
msft_data tdl_ff_1_ch_0_n(.rst(rst), .clk(clk), .clk_en(clk_en), .we(data_ld), .data_in(tdl_dat_0_n),.data_out(tdl_dat_1_n));
defparam tdl_ff_1_ch_0_n.WIDTH = 12;
defparam tdl_ff_1_ch_0_n.LENGTH = 4;
defparam tdl_ff_1_ch_0_n.DELAY = 0;
msft_data tdl_ff_2_ch_0_n(.rst(rst), .clk(clk), .clk_en(clk_en), .we(data_ld), .data_in(tdl_dat_1_n),.data_out(tdl_dat_2_n));
defparam tdl_ff_2_ch_0_n.WIDTH = 12;
defparam tdl_ff_2_ch_0_n.LENGTH = 4;
defparam tdl_ff_2_ch_0_n.DELAY = 0;
msft_data tdl_ff_3_ch_0_n(.rst(rst), .clk(clk), .clk_en(clk_en), .we(data_ld), .data_in(data_in_mux2),.data_out(tdl_dat_3_n_ori));
defparam tdl_ff_3_ch_0_n.WIDTH = 12;
defparam tdl_ff_3_ch_0_n.LENGTH = 4;
defparam tdl_ff_3_ch_0_n.DELAY = 0;
msft_data tdl_ff_4_ch_0_n(.rst(rst), .clk(clk), .clk_en(clk_en), .we(data_ld), .data_in(tdl_dat_3_n_ori),.data_out(tdl_dat_4_n));
defparam tdl_ff_4_ch_0_n.WIDTH = 12;
defparam tdl_ff_4_ch_0_n.LENGTH = 4;
defparam tdl_ff_4_ch_0_n.DELAY = 0;
msft_data tdl_ff_5_ch_0_n(.rst(rst), .clk(clk), .clk_en(clk_en), .we(data_ld), .data_in(tdl_dat_4_n),.data_out(tdl_dat_5_n_pre));
defparam tdl_ff_5_ch_0_n.WIDTH = 12;
defparam tdl_ff_5_ch_0_n.LENGTH = 3;
defparam tdl_ff_5_ch_0_n.DELAY = 0;
lc_store_cen Udata_comp(.clk(clk), .ce(1'b1), .rst(rst),.gclk_en(clk_en),.data_in(tdl_dat_5_n_pre), .q(tdl_dat_5_n) );
defparam Udata_comp.WIDTH = 12;
mux_2to1_comb sym_mux(.rst(rst),.bin(tdl_dat_3_n_ori),.ain(12'b0),
.data_out(tdl_dat_3_n),.sel(rdy_int));
defparam sym_mux.IN_WIDTH = 12;

// symmetrical adders ...
wire [12:0] sym_res_0_n;
sadd_cen U_0_sym_add (.clk(clk), .gclk_en(clk_en), .ain(tdl_dat_0_n), .bin(tdl_dat_5_n), .res(sym_res_0_n) );
defparam U_0_sym_add.IN_WIDTH = 12;
defparam U_0_sym_add.PIPE_DEPTH = 1;
wire [12:0] sym_res_1_n;
sadd_cen U_1_sym_add (.clk(clk), .gclk_en(clk_en), .ain(tdl_dat_1_n), .bin(tdl_dat_4_n), .res(sym_res_1_n) );
defparam U_1_sym_add.IN_WIDTH = 12;
defparam U_1_sym_add.PIPE_DEPTH = 1;
wire [12:0] sym_res_2_n;
sadd_cen U_2_sym_add (.clk(clk), .gclk_en(clk_en), .ain(tdl_dat_2_n), .bin(tdl_dat_3_n), .res(sym_res_2_n) );
defparam U_2_sym_add.IN_WIDTH = 12;
defparam U_2_sym_add.PIPE_DEPTH = 1;


wire coef_en ;
assign coef_en = clk_en;
wire [11:0] coef_st_comb_0_n;
wire [COEF_WIDTH-1:0]coef_st_0_n;
assign coef_st_0_n = coef_st_comb_0_n[11:0];
msft_lt_32 Ucoef_0_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(12'b0), .data_out(coef_st_comb_0_n));
defparam Ucoef_0_n.WIDTH = COEF_WIDTH;
defparam Ucoef_0_n.LENGTH = 4;
defparam Ucoef_0_n.DELAY = 0;
defparam Ucoef_0_n.C0 = 0;
defparam Ucoef_0_n.C1 = 0;
defparam Ucoef_0_n.C2 = 567;
defparam Ucoef_0_n.C3 = 4018;
wire [11:0] coef_st_comb_1_n;
wire [COEF_WIDTH-1:0]coef_st_1_n;
assign coef_st_1_n = coef_st_comb_1_n[11:0];
msft_lt_32 Ucoef_1_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(12'b0), .data_out(coef_st_comb_1_n));
defparam Ucoef_1_n.WIDTH = COEF_WIDTH;
defparam Ucoef_1_n.LENGTH = 4;
defparam Ucoef_1_n.DELAY = 0;
defparam Ucoef_1_n.C0 = 92;
defparam Ucoef_1_n.C1 = 0;
defparam Ucoef_1_n.C2 = 1575;
defparam Ucoef_1_n.C3 = 3769;
wire [11:0] coef_st_comb_2_n;
wire [COEF_WIDTH-1:0]coef_st_2_n;
assign coef_st_2_n = coef_st_comb_2_n[11:0];
msft_lt_32 Ucoef_2_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(12'b0), .data_out(coef_st_comb_2_n));
defparam Ucoef_2_n.WIDTH = COEF_WIDTH;
defparam Ucoef_2_n.LENGTH = 4;
defparam Ucoef_2_n.DELAY = 0;
defparam Ucoef_2_n.C0 = 112;
defparam Ucoef_2_n.C1 = 4061;
defparam Ucoef_2_n.C2 = 2047;
defparam Ucoef_2_n.C3 = 3901;


wire [24:0] mlu_resx_0_n;
mlu_inf_2reg Umlu_0_n (.clk(clk), .data_in(sym_res_0_n), .coef_in(coef_st_0_n), .clk_en(clk_en), .mlu_out(mlu_resx_0_n) );
defparam Umlu_0_n.DATA_WIDTH = 13;
defparam Umlu_0_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_0_n.PIPE = 2;
defparam Umlu_0_n.DSP_USE = "YES";
wire [24:0] mlu_res_0_n;
mac_tl Umtl_0_n             (.clk(clk), 
             .data_in(mlu_resx_0_n),
             .data_out(mlu_res_0_n));
defparam Umtl_0_n.DATA_WIDTH = 25;

wire [24:0] mlu_resx_1_n;
mlu_inf_2reg Umlu_1_n (.clk(clk), .data_in(sym_res_1_n), .coef_in(coef_st_1_n), .clk_en(clk_en), .mlu_out(mlu_resx_1_n) );
defparam Umlu_1_n.DATA_WIDTH = 13;
defparam Umlu_1_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_1_n.PIPE = 2;
defparam Umlu_1_n.DSP_USE = "YES";
wire [24:0] mlu_res_1_n;
mac_tl Umtl_1_n             (.clk(clk), 
             .data_in(mlu_resx_1_n),
             .data_out(mlu_res_1_n));
defparam Umtl_1_n.DATA_WIDTH = 25;

wire [24:0] mlu_resx_2_n;
mlu_inf_2reg Umlu_2_n (.clk(clk), .data_in(sym_res_2_n), .coef_in(coef_st_2_n), .clk_en(clk_en), .mlu_out(mlu_resx_2_n) );
defparam Umlu_2_n.DATA_WIDTH = 13;
defparam Umlu_2_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_2_n.PIPE = 2;
defparam Umlu_2_n.DSP_USE = "YES";
wire [24:0] mlu_res_2_n;
mac_tl Umtl_2_n             (.clk(clk), 
             .data_in(mlu_resx_2_n),
             .data_out(mlu_res_2_n));
defparam Umtl_2_n.DATA_WIDTH = 25;

wire [25:0] tree_l_0_n_0_n;
sadd_reg_top_cen Uaddl_0_n_0_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_0_n), .bin(mlu_res_1_n), .res(tree_l_0_n_0_n) );
defparam Uaddl_0_n_0_n.IN_WIDTH = 25;
defparam Uaddl_0_n_0_n.PIPE_DEPTH = 1;
wire [25:0] tree_l_0_n_1_n;
sadd_reg_top_cen Uaddl_0_n_1_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_2_n), .bin(25'd0), .res(tree_l_0_n_1_n) );
defparam Uaddl_0_n_1_n.IN_WIDTH = 25;
defparam Uaddl_0_n_1_n.PIPE_DEPTH = 1;

wire [26:0] tree_l_1_n_0_n;
sadd_reg_top_cen Uaddl_1_n_0_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_0_n_0_n), .bin(tree_l_0_n_1_n), .res(tree_l_1_n_0_n) );
defparam Uaddl_1_n_0_n.IN_WIDTH = 26;
defparam Uaddl_1_n_0_n.PIPE_DEPTH = 1;

wire [26:0] fir_mc_res;
assign fir_mc_res=tree_l_1_n_0_n;
wire [24:0] fir_acc_in;
wire [24:0] fir_temp_res;
wire [24:0] fir_acc_in_reg;
assign fir_acc_in = fir_mc_res[ACCUM_WIDTH-1:0];
lc_store_cen Uaccum_reg (.clk(clk), .ce(1'b1), .gclk_en(clk_en),.rst(rst), .data_in(fir_acc_in), .q(fir_acc_in_reg) );
defparam Uaccum_reg.WIDTH = ACCUM_WIDTH;
maccum_cen Usa (.clk(clk), .gclk_en(clk_en),.rst(acc_rst_out), .ain(fir_acc_in_reg), .accum_out(fir_temp_res));
defparam Usa.WIDTH_A = ACCUM_WIDTH;
wire [24:0] fir_int_res;
lc_store_cen Ures_reg (.clk(clk), .ce(done_int), .rst(rst), .gclk_en(clk_en),.data_in(fir_temp_res[ACCUM_WIDTH-1:0]), .q(fir_int_res) );
defparam Ures_reg.WIDTH = ACCUM_WIDTH;
assign fir_result = fir_int_res;
mcv_ctrl_nc ctrl(.rst(rst), .clk(clk), .acc_rst_out(acc_rst_out),.clk_en(clk_en),
 .done_int(done_int), .rdy_int(rdy_int), .coef_ld(coef_ld), 
.done(done), .data_ld(data_ld), .rdy_to_ld(rdy_to_ld));
defparam ctrl.REG_LEN   = 4;
defparam ctrl.PIPE_DLY  = 6;
defparam ctrl.BASE_CYCLE  = 4;
defparam ctrl.NO_SYM   = 0; 
defparam ctrl.IS_INT   = 0; 

endmodule
